version: "3"

services:
  syncer:
    image: ghcr.io/f466162/mailboxsyncer:edge
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/data
    secrets:
      - from_secret_file
      - to_secret_file

secrets:
  from_secret_file:
    file: ...
  to_secret_file:
    file: ...